### ISSUE TITLE
[EPIC] Move in

### ISSUE THREAD

**Issue by palexster** [LiqoTech/liqo#1]
To do:
- [x] Update repository
- [x] Rename all the packages
- [x] Move CI to self-hosted runner
- [x] Fix all CI pipellines 
- [x] Fix GO fmt errors
