### ISSUE TITLE
[Feature] Uninstall Script

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#153]
**Is your feature request related to a problem? Please describe.**

So far, it is very complex to correctly uninstall all the liqo resources.

**Describe the solution you'd like**

Similarly to install.sh script, we should have a uninstall.sh script to safely remove all liqo objects.

**Describe alternatives you've considered**

Liqo uninstall is uncomfortable and requires to have helminstalled and liqo repository downloaded.

Steps:

- [x] Implement Uninstall function (Ref. #185)
- [x] Linting Shellcheck (Ref. #229)
- [x] Sleep deletion + Auto-crt approval (Ref. #232)
- [ ] Default mode: Install the latest "stable" release
- [x] Checkout tagged releases
