### ISSUE TITLE
[Epic] Virtual Kubelet Enhancements

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#170]
**Is your feature request related to a problem? Please describe.**

So far, the Liqo implementation of virtual-kubelet still misses support for several features:

Virtual Kubelet Interface:
- [ ] kubectl cp
- [ ] kubectl port-forward
- [ ] kubelet metrics exported

Reflector Issues:

- [x] EndpointSlice Support
- [x] Default Namespace issues (ref. #157)

Liqo Exploration:

- [x] Linking advertisement to Virtual Node (#227)

**Comment by palexster** [comment]
Closing in favor of #367
