### ISSUE TITLE
[Feature] Resliency to clusters failures

### ISSUE THREAD

**Issue by Fra98** [liqotech/liqo#1705]
The remote cluster is not resilient to failures of the local cluster (i.e., the one doing the offloading). Requests to pods running on the local cluster will fail if the local cluster is unhealthy, resulting in service disruption.

Resiliency could be achieved by invalidating endpoints of the local pods if at least one of the following scenarios occurs:
* Local cluster not reachable through the VPN tunnel (TunnelEndpoint)
* Local cluster's API server is unhealthy (unreachable or not ready)

In this way, services do not redirect the traffic towards local pods, ensuring service continuity.

### Required steps
* [x] 1) Implement a controller that, in the remote cluster,sets the status of the local pods endpoints to Ready/NotReady depending on whether the local cluster is reachable via the TunnelEndpoint #1677
* [x] 2) Add a new status condition in the ForeignCluster CR that tracks the readiness status of the foreign API server #1703
* [x] 3) Update the new controller to also check for failures of the local API server using the new status condition added in step 2 #1774 
* [x] 4) Change the API server check of the virtual kubelet: it should simply monitor the new status condition added in step 2 #1820
