### ISSUE TITLE
[Feature] Move API version to v1alpha1

### ISSUE THREAD

**Issue by palexster** [LiqoTech/liqo#188]
**Is your feature request related to a problem? Please describe.**
As discussed in last meetings, most APIs are still in version 1 which is kind of premature is this phase. They should move to v1alpha1.

Families:

- [x] advertisement-operator --> sharing (@fraborg Ref. #208)
- [x] clusterconfig --> config (@palexster Ref. #192)
- [x] liqonet -> net (@alacuku #221)
- [x] namespaceNattingTable --> virtualkubelet (@mLavacca #209 )
- [x] schedulingNode-operator --> scheduling (@mLavacca #209 )
