### ISSUE TITLE
Network Connectivity Improvement

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#2]
* RouteOperator
  * [x] Dynamically join new nodes, when added to the cluster, to the vxlan overlay network;

* TunnelOperator
  * [x] A driver to install tunnels using different technologies. Only GRE tunnel is supported now;
  * [x] Auto negotiation of network parameters between the cluster, like the private ip tunnel; (Ref. #151, #173 )

* All modules
  * [x] Add persistence of the network configuration using a new CRD (Ref. #151)
  * [x] Support dynamic changes to the network configuration without the need to destroy and recreate the network custom resources (Ref. #280, #266, #268)

**Comment by palexster** [comment]
Hi @alacuku is this still updated to the state of implementation?

**Comment by palexster** [comment]
Hi @alacuku, is this addressed by #374?
