### ISSUE TITLE
Broadcaster refactoring

### ISSUE THREAD

**Issue by giuse2596** [liqotech/liqo#548]
This issue describes all steps to follow to get a complete refactor of Peering phase between two clusters. 
PeeringRequest CR will be replaced by ResourceRequest  CR, Advertisement CR will be replaced by ResourceOffer CR, a new controller will be created to Reconcile ResourceRequests and create new ResourceOffer locally. A new version of Broadcaster has the function of starting an Informer to watch nodes and pods and then export all cluster resources available which can be offered in ResourceOffer. Finally an update logic of ResourceOffer will be created. 

TODO list:

- [x] APIs for  Resource Request and Resource Offer #552 
- [x] Resource Offer controller with static resources #560 
- [x] Logic to watch nodes #595 
- [x] Resource Offer updates
- [x] Pods Updates #654 
- [x] Switch to the new version

**Comment by palexster** [comment]
Closing as completely addressed.
