### ISSUE TITLE
[Feature] Support for deployments spanning across selected clusters.

### ISSUE THREAD

**Issue by Andreagit97** [liqotech/liqo#572]
# Description

So far when Users deploy apps using Liqo, they do not have the opportunity to choose which remote clusters use to offload their workload. This new feature allows you to select specif remote clusters according to defined requirements by simply creating a custom resource called NamespaceOffloading.

# Required Steps

- [x]  **STEP 1**: Introduce a new `NamespaceMap` CRD that will replace `NamespaceNattingTable` resource. #569 

- [x]  **STEP  2**: 
     - Implement a new Virtual-node Controller that spawns `NamespaceMaps` corresponding to just created `VirtualNodes`. This controller takes also care of `NamespaceMaps`' and `VirtualNodes`' deletion lifecycle. #561 
     - Implement a new Namespace Controller that watches `Namespace`'s labels and decides if a `Namespace` has to be offloaded onto a remote cluster or not. #571 

- [x]  **STEP 3**:
    - Implement a new NamespaceMap Controller that watches `NamespaceMap`'s Spec to understand which `Namespaces` have to offloaded onto the remote cluster, and updates `NamespaceMap`'Status with the current state of the just created remote `Namespaces`. #587
    - `NamespaceMap`'s refactor due to new features introduced by NamespaceMap Controller. #585
 
- [x]  **STEP 4**: Possibility to specify, at installation time, cluster's labels; these labels must be inserted in `ClusterConfig` CRD with all other information about the cluster.   #597

- [x]  **STEP 5**: Cluster's labels (of the previous step) must be imported into `ResourceOffer` CRD, so that VirtualKubelet could expose them on the corresponding `VirtualNodes`. #720 

- [x]  **STEP 6**: Introduce a new `NamespaceOffloading` CRD that allows the user to specify, with desired granularity, on which cluster his workload must be offloaded. #617

- [x]  **STEP 7**: Refactor of Namespace controller in order to support `NamespaceOffloading` management. #639 

- [x]  **STEP 8**: New features for NamespaceMap Controller: #643 
    
- When there is a problem in remote namespace creation onto a remote cluster, the associated `NamespaceMap` is updated with a Refused phase for that namespace (`Status`->`CurrentMapping`->` RemoteStatus`->` Phase`=Refused). The NamespaceMap Controller will try to create that Namespace until the problem will be solved with exponential backoff.

- The controller updates the remote namespace condition in the `NamespaceOffloading` resource associated with the just created remote namespace.

- [x]  **STEP 9**: New NamespaceOffloading controller; this controller gets a just created `NamespaceOffloading` resource and adds entries to `NamespaceMaps` (`Spec`->` DesiredMappings`) in order to require the creation of remote namespaces, based on requirements specified by users. #644 

- [x]  **STEP 10**: New OffloadingStatus controller; This new controller waits for all remote conditions of the offloaded namespace, and when the controller is able to get all of them, it sets the global offloading status according to these remote conditions. #645 

- [x]  **STEP 11**: Refactor of VirtualNode controller; now it has only to manage the NamespaceMap regeneration in case of deletion. #699 

- [x]  **STEP 12**: Modify Webhook's logic so that `Pods` receive the right `NodeAffinity`, enabling offloading only inside selected remote clusters. #591 

- [x]  **STEP 13**: Activate the new controllers of the liqo controller manager and move `NamespaceMaps` resources in specific Namespaces (`Tenant Namespaces`). #702 

- [x]  **STEP 14**: Refactor of Virtualkubelet's functionalities; only NAT and DENAT operation and transition from  `NamespaceNattingTables` to `NamespaceMap` resource. #717 

- [x]  **STEP 15**: Add checks on the privileges that the NamespaceMap controller has when creates the remote namespaces. #723 

- [x]  **STEP 16**: Activate the new webhook logic. #726

**Comment by palexster** [comment]
Closing since completely addressed.
