### ISSUE TITLE
Authentication and PeeringProcess Refactoring

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#573]
# Description

This issue tracks the migration from the ServiceAccount-based authentication to the new Certificate-based authentication, with the usage of namespaced resources

# Steps

### General
- [x] define cluster roles in the helm chart - #580
  - Network Resources
  - Advertisement
  - Resource Request
- [ ] namespaced resources
  - all the Liqo resources, but not the ForeignCluster

### ForeignCluster Operator (Authentication)
- [x] "system" namespace creation - #574 #588
- [x] certificate creation - #578 #588
- [x] store remote system namespace name in the ForeignCluster - #588
- [ ] switch to the new auth endpoint (after auth 4) - #588
- [ ] certificate rotation (after CrdR 2)
  - set shorter time
  -  create a new certificate when deadline is near
  -  recreate all the clients pointing to the remote cluster

### Authentication Service
- [x] create a new HTTP endpoint - #583 
- [x] CRS approval - #578 #583
- [x] "system" namespace creation - #574 #583
- [x] create role binding (resource request and network resources) in the "system" namespace - #574 #583
- [ ] allow only certificates with a short time to live (after FC Op Auth 5)

### ForeignCluster Operator (Peering)
- [x] create role binding (advertisement and network resources) in the "system" namespace - #574 #588
- [x] create local ResourceRequest in the “system” namespace - #588
- [ ] enable cr replication (after CrdR 1) - #663 
- [ ] delete the cluster scoped PeeringRequest (when the broadcaster is able to handle the new resource)

### CrdReplicator
- [x] allow different source and destination namespaces - #632
- [x] enable the replication of CRDs in different peering phases - #649 #663 
- [ ] allow client recreation when the client identity is updated

### ResourceOffer Operator (Peering / Node Creation)
- [x] add the new operator - #637 
- [x] filter only replicated resources - #637 
- [x] set the phase accordingly - #637 
- [x] add vk cluster role - #646  
- [x] create virtual node - #653 
  - role binding
  - create deployment
  - manage lifecycle
