### ISSUE TITLE
[Roadmap] E2E Testing

### ISSUE THREAD

**Issue by palexster** [LiqoTech/liqo#79]
**Is your feature request related to a problem? Please describe.**

In order to improve the testing of Liqo, we would like to add testing on real Liqo Deployments

## Steps

* [x] Handle cluster lifecycle
     * [x] Create different clusters for different PRs
     * [x] Delete the right VMs
* [x] Create a feedback loop to build clusters:
    * [x] Deploy one cluster + Liqo Install
    * [x] Get the feedback loop* 
* [x] Add Assertions

**Comment by palexster** [comment]
Closing. Fixed by #80.
