### ISSUE TITLE
[Feature] Support for OpenShift

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#909]
# Description

This issue tracks the support for OpenShift Kubernetes distribution

# Steps

- [x] support for the OwnerReferencesPermissionEnforcement Admission Controller - #896 
- [x] disable the discovery component (it is useless, and causes troubles)
    - move the operators to the liqo controller manager - #902
    - remove the clusterID creation - #908
    - disable the deployment - #910 
- [x] add SecurityContextConstraints (`privileged`, `anyuid`) - #914 
    - `liqo-route`
    - `liqo-gateway`
    - ~~`liqo-auth`~~
- [x] add dedicated `liqoctl install` provider - #914

**Comment by palexster** [comment]
Closing since addressed by #914
