### ISSUE TITLE
[Feature] Liqo Persistent Storage Support

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#944]
**Is your feature request related to a problem? Please describe.**
Introduce a virtual storage class to allow support for stateful workloads. 

**Describe the solution you'd like**
Implement a virtual storage class that maps virtual PV on actual PV of cluster's storage classes.

### Out of Scope

- [x] Inter-cluster persistent storage replication

## Steps

- [x] Define a Liqo StorageClass - #973 
- [x] Create a provider for the StorageClass - #979 
- [x] Implement the advertising logic of storage classes in the ResourceOffer - #998 
- [x] Implement the logic for local pods - #974
- [x] Implement the logic for remote pods - #991 
- [x] ~Inform scheduler about the binded volumes (nodes attached) handled in the VK~ (handled by PV's nodeSelector)
- [x] update the capsule subchart - #999
- [x] e2e tests - #1004
